"""PRD §8.1 inputs and README conversion ratios (test SSOT)."""

METER_TO_FEET = 3.28084
METER_TO_YARD = 1.09361

SUPPORTED_UNITS = ("meter", "feet", "yard")

PRD_S2_VALUE = 2.5
PRD_S2_UNIT = "meter"
PRD_S2_INPUT = f"{PRD_S2_UNIT}:{PRD_S2_VALUE}"

PRD_S4_INPUT = PRD_S2_INPUT

PRD_S1_FORMAT_INPUT = "meter"
PRD_S1_UNKNOWN_UNIT = "inch"
PRD_S1_UNKNOWN_VALUE = 1.0
PRD_S1_UNKNOWN_INPUT = f"{PRD_S1_UNKNOWN_UNIT}:{PRD_S1_UNKNOWN_VALUE:g}"
PRD_S1_NUMBER_INPUT = "meter:abc"

PRD_FR5_REGISTER_INPUT = "1 cubit = 0.4572 meter"
PRD_FR5_UNIT = "cubit"
PRD_FR5_VALUE = 1.0
CUBIT_METERS_PER_UNIT = 0.4572

S3_MOCK_UNIT = "fathom"
S3_MOCK_METERS_PER_UNIT = 1.8288
S3_MOCK_VALUE = 2.0

U02_INVALID_FORMAT = "meter"
PRD_U03_CONVERT_INPUT = "cubit:2"
PRD_U03_VALUE = 2.0
PRD_U03_STDIN = f"{PRD_FR5_REGISTER_INPUT}\n{PRD_U03_CONVERT_INPUT}\n"
